### ISSUE TITLE
container style height 100% overwritten after first transition

### ISSUE THREAD

**Issue by jonlachlan** [jamielob/transitions#9]
I set my container style height to 100% in css, however after my first transition the height is reset to the current height of the browser window. When I inspect the html elements on the page, there's an inline style for `height` that is added.

I was able to avoid this by adding `!important` to the `.transitions-container` css:

``` css
.transitions-container
 {
  height:100% !important;
}
```

It would be nice if I didn't need to have the `!important` flag...
